Goalvisor/Controllers/AffiliateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Goalvisor.Helper;
using Goalvisor.Models;
using Goalvisor.Services.Affiliate;
using Goalvisor.ViewModels.Core;
using Goalvisor.ViewModels.DataTables.Base;
using System;
using System.Threading.Tasks;

namespace Goalvisor.Controllers
{
    [Authorize]
    public class AffiliateController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAffiliateService _affiliateService;
        public string baseUrl { get; set; }

        public AffiliateController(UserManager<ApplicationUser> userManager, IAffiliateService affiliateService)
        {
            _affiliateService = affiliateService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GenerateLink()
        {
            ViewBag.baseurl = PathHelper.FullyQualifiedApplicationPath(ControllerContext.HttpContext.Request) + "join?r=";
            return View();
        }

        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.baseUrl = PathHelper.FullyQualifiedApplicationPath(ControllerContext.HttpContext.Request) + "join?r=";
            ReferralLink referralLink;
            if (id != 0)
            {
                referralLink = await _affiliateService.GetById(id);
                string[] customUrl = referralLink.ReferralUrl.Split('=');
                referralLink.ReferralUrl = customUrl[1];
                if (referralLink == null)
                {
                    return BadRequest();
                }
            }
            else
            {
                referralLink = new ReferralLink();
            }
            return PartialView(referralLink);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await _affiliateService.DeleteById(id);
            return new JsonResult(result);
        }

        public IActionResult MyReferralLinks()
        {
            return View();
        }

        public IActionResult ReferralDetails(int id = 0)
        {
            ViewData["linkId"] = id;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddEdit(ReferralLink referralLink)
        {
            baseUrl = PathHelper.FullyQualifiedApplicationPath(ControllerContext.HttpContext.Request) + "join?r=";
            ViewBag.baseUrl = baseUrl;
            referralLink.GenerateDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                referralLink.UserId = user.Id;
                referralLink.ReferralUrl = baseUrl + referralLink.ReferralUrl;
                var checkExist = _affiliateService.GetByLink(referralLink.ReferralUrl);
                if (referralLink.Id <= 0)
                {
                    if (checkExist != null)
                    {
                        if (checkExist.Id > 0)
                        {
                            TempData["ErrorMsg"] = "The link " + referralLink.ReferralUrl + " already exists!";
                            return View("GenerateLink", referralLink);
                        }
                    }
                }
                else
                {
                    checkExist = await _affiliateService.GetByLinkAndId(referralLink.ReferralUrl, referralLink.Id);
                    if (checkExist != null)
                    {
                        if (checkExist.Id > 0)
                        {
                            TempData["ErrorMsg"] = "The link " + referralLink.ReferralUrl + " already exists!";

                            return View("Edit", referralLink);
                        }
                    }
                }
                var result = await _affiliateService.AddEditLink(referralLink);
                TempData["SuccessMsg"] = result.Message;

                if (User.IsInRole(RunTimeElements.AdministratorRole))
                {
                    return RedirectToAction("List");
                }
                else
                    return RedirectToAction("MyReferralLinks");
            }
            else
            {
                if (referralLink.Id > 0)
                {
                    return View("Edit", referralLink);
                }
                else
                    return View("GenerateLink", referralLink);
            }
        }

        [HttpPost]
        public async Task<IActionResult> PageData(DataTablesRequest request)
        {
            var result = await _affiliateService.DataTable(request, 0);
            return new JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> PageDataUser(DataTablesRequest request)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var result = await _affiliateService.DataTable(request, user.Id);
            return new JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> GetReferLinkHistoryByLinkId(DataTablesRequest request, int id)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var result = await _affiliateService.GetReferLinkHistoryByLinkId(request, user.Id, id);
            return new JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> GetByUserId()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var result = _affiliateService.GetByUserId(user.Id);
            return new JsonResult(result);
        }
    }
}

Goalvisor/Controllers/MyAccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Goalvisor.Helper;
using Goalvisor.Services.Subscriptions;
using Goalvisor.Services.Users;
using Goalvisor.ViewModels;
using Goalvisor.ViewModels.DataTables.Base;
using Stripe;
using System;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Goalvisor.Controllers
{
    [Authorize]
    public class MyAccountController : Controller
    {
        private readonly IUserService _userService;
        private readonly IConfiguration _configuration;
        private readonly ISubscriptionsService _subscriptionsService;

        public MyAccountController(IUserService userService, IConfiguration configuration, ISubscriptionsService subscriptionsService)
        {
            _userService = userService;
            _configuration = configuration;
            _subscriptionsService = subscriptionsService;
        }

        [HttpPost]
        public async Task<IActionResult> Subscriptions(int id, DataTablesRequest request)
        {
            var user = await _userService.GetByName(HttpContext.User.Identity.Name);
            var data = await _userService.Subscriptions(user.Id, request);
            return new JsonResult(data);
        }

        public async Task<IActionResult> Index(string subId)
        {
            ViewData["RootURL"] = _configuration.GetValue<string>("Root");

            var user = await _userService.GetByName(HttpContext.User.Identity.Name);
            if (!string.IsNullOrEmpty(subId))
            {
                StripeConfiguration.ApiKey = StripeUtil.SecretKey;
                var service = new SubscriptionService();
                var subscriptionResponse = await service.CancelAsync(subId, null);
                if (subscriptionResponse.Status == "canceled")
                {
                    await _subscriptionsService.DeleteById(subId);
                }
            }
            return View(user);
        }

        public async Task<IActionResult> UpdateInfo()
        {
            return PartialView(await _userService.GetByName(HttpContext.User.Identity.Name));
        }

        [HttpPost]
        public async Task<IActionResult> UpdateInfo(UserVM user)
        {
            var result = await _userService.Update(user);
            return new JsonResult(result);
        }

        public async Task<IActionResult> UpdateReferralId()
        {
            ViewData["RootURL"] = _configuration.GetValue<string>("Root");
            ViewData["codeLength"] = _configuration.GetValue<string>("ReferralCodeMaxLength");
            return PartialView(await _userService.GetByName(HttpContext.User.Identity.Name));
        }

        [HttpPost]
        public async Task<bool> UpdateReferralId(UserVM user)
        {
            bool isValid = ValidateRequest(user);
            if (isValid)
            {
                bool result = await _userService.UpdateReferralCode(user);
                return result;
            }
            else
            {
                return false;
            }
        }

        [HttpPost]
        public async Task<bool> IsUniqueReferralCode(int r)
        {
            return await _userService.IsUniqueReferralCode(r);
        }

        #region "Private Methods"

        private bool ValidateRequest(UserVM user)
        {
            //This is for server side validations.
            //Not using data annotation for validation as it may cause issue with existing data
            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (user.Id == Convert.ToInt32(userId))
                //if (isAlphaNumeric(user.ReferralCode) && user.ReferralCode.Length <= _configuration.GetValue<int>("ReferralCodeMaxLength"))
                //    return true;
                //else
                //    return false;
                return true;
            else
                return false;
        }

        private bool isAlphaNumeric(string referralCode)
        {
            Regex rg = new Regex(@"^[a-zA-Z0-9\s,]*$");
            return rg.IsMatch(referralCode);
        }

        #endregion "Private Methods"
    }
}

Goalvisor/Controllers/ScannerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Goalvisor.ViewModels.Core;

namespace Goalvisor.Controllers
{
    [Authorize(Policy = RunTimeElements.SubscriberOrAdminPolicy)]
    public class ScannerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Goalvisor/Controllers/SubscriptionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Goalvisor.Helper;
using Goalvisor.Models;
using Goalvisor.Services.Subscriptions;
using Goalvisor.ViewModels;
using Goalvisor.ViewModels.Core;
using Goalvisor.ViewModels.DataTables.Base;
using System.Net;
using System.Threading.Tasks;

namespace Goalvisor.Controllers
{
    [Authorize]
    public class SubscriptionsController : Controller
    {
        private readonly ISubscriptionsService _subscriptionsService;

        public SubscriptionsController(ISubscriptionsService subscriptionsService)
        {
            _subscriptionsService = subscriptionsService;
        }

        public async Task<IActionResult> MySubscriptions(string subId)
        {
            if (!string.IsNullOrEmpty(subId))
            {
                try
                {
                    Stripe.StripeConfiguration.ApiKey = Helper.StripeUtil.SecretKey;
                    var service = new Stripe.SubscriptionService();
                    var subscriptionResponse = await service.CancelAsync(subId, null);
                    if (subscriptionResponse.Status == "canceled")
                    {
                        await _subscriptionsService.DeleteById(subId);
                    }
                }
                catch (System.Exception)
                {
                    return View();
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> PageData(DataTablesRequest request)
        {
            var result = await _subscriptionsService.DataTable(request);
            return new JsonResult(result);
        }

        [Authorize(Policy = RunTimeElements.AdministratorRole)]
        public async Task<IActionResult> Edit(int id)
        {
            Subscription subscription = null;

            subscription = await _subscriptionsService.GetById(id);
            if (subscription == null)
            {
                return BadRequest();
            }
            var vm = new SubscriptionVM
            {
                Duration = subscription.Duration,
                EndDate = subscription.EndDate,
                StartDate = subscription.StartDate,
                Id = subscription.Id,
                PackageName = subscription.Package.Name,
                UserName = subscription.User.FullName,
                Expired = subscription.Expired,
                PackageId = subscription.PackageId,
                UserId = subscription.UserId,
                Active = subscription.Active
            };
            return PartialView(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Subscription subscription)
        {
            var result = await _subscriptionsService.Update(subscription);

            return new JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            var result = await _subscriptionsService.DeleteById(id);

            return new JsonResult(result);
        }

        public JsonResult GetSubscriptionDetail(string subScriptionId)
        {
            try
            {
                if (string.IsNullOrEmpty(subScriptionId))
                {
                    return Json(new { ok = false, msg = "Invalid Subscription Id." });
                }

                Stripe.StripeConfiguration.ApiKey = StripeUtil.SecretKey;

                var service = new Stripe.SubscriptionService();
                var subscription = service.Get(subScriptionId);
                HttpStatusCode StatusCode = subscription.StripeResponse.StatusCode;
                if (StatusCode == HttpStatusCode.OK)
                {
                    return Json(new
                    {
                        BillingCycleAnchor = subscription.BillingCycleAnchor,
                        CollectionMethod = subscription.CollectionMethod,
                        CurrentPeriodStart = subscription.CurrentPeriodStart,
                        CurrentPeriodEnd = subscription.CurrentPeriodEnd,
                        Quantity = subscription.Quantity,
                        Status = subscription.Status,
                        Amount = subscription.Plan.Amount / 100,
                        BillingScheme = subscription.Plan.BillingScheme,
                        Created = subscription.Plan.Created,
                        Currency = subscription.Plan.Currency,
                        Interval = subscription.Plan.Interval,
                        Active = subscription.Plan.Active
                    });
                }
                return null;
            }
            catch (System.Exception ex)
            {
                return Json(new { ok = false, msg = "Exception occured." });
            }
        }

        public IActionResult Details(int id)
        {
            var subscription = _subscriptionsService.GetById(id);
            if (subscription == null)
            {
                return BadRequest();
            }
            return PartialView(subscription);
        }

        [Authorize(Policy = RunTimeElements.AdministratorRole)]
        public IActionResult Delete(int id)
        {
            _subscriptionsService.DeleteById(id);
            return Ok();
        }
    }
}

Goalvisor/Views/Admin/Affiliates.cshtml
@{ ViewData["Title"] = "Manage Affiliates";
                Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

<div>
    <div class="float-left">
        <h1>Referral Links</h1>
    </div>
    <div class="float-right">

        <a class="btn btn-info" asp-area="" asp-controller="Affiliate" asp-action="GenerateLink">Create Referral Link</a>
    </div>
    <div class="clearfix" style="width:100%"></div>
</div>
<div class="pb-5">
    <table id="referraltbl" class="table table-bordered table-hover dataTable" style="width:100%">
        <thead>
            <tr>
                <td style="width:15%">Name</td>
                <td style="width:30%">Referral Url</td>
                <td style="width:30%">Username</td>
                <td style="width:52%">Date</td>
                <td style="width:3%">Actions</td>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

<div class="clearfix pb-5" style="width:100%"></div>

@section Scripts{
    <script>
        let table = {};
        $(document).ready(function () {
            table = $('#referraltbl').DataTable({
                "searchable": true,
                "bDestroy": true,
                "ordering": true,
                "serverSide": true,
                responsive: true,
                processing: true,
                sortable: true,
                ajax: {
                    "url": "/Affiliate/PageData",
                    "type": "POST"
                },
                columns: [
                    {
                        name: 'Name',
                        data: 'name',
                        title: "Name",
                        sortable: true,
                    },
                    {
                        name: 'referralUrl',
                        data: 'referralUrl',
                        title: "Referral Url",
                        sortable: true,
                    },
                    {
                        name: 'userName',
                        data: 'userName',
                        title: "Username",
                        sortable: true,
                    },
                    {
                        name: 'Generate Date',
                        data: 'generateDate',
                        title: "Date",
                        sortable: true
                    },
                    {
                        name: 'Action',
                        data: null,
                        targets: -1,
                        sortable: false,
                        title: 'Action',
                        searchable: false,
                        "render": function (data, type, full, meta) {
                            return generateActionButtons(full.id);
                        }
                    }
                ]
            });
           var CreateSuccessMsg = "@(TempData["SuccessMsg"] as string)";
              var  ErrMsg = "@(TempData["ErrorMsg"] as string)";

        if (CreateSuccessMsg !== "") {

            notifySucess(CreateSuccessMsg);
            }
            if (ErrMsg !== "") {

                notifyError(ErrMsg);
            }

        });

        function Update(id) {
            var modalSelector = GetLoaderModal(80);
            $(modalSelector).modal();

            $(modalSelector + "-content").load("/Affiliate/Edit/" + id,
                function (response, status, xhr) {
                }
            );
        }
        function remove(eferralId) {
            Swal.fire({
                title: 'Are you sure?',
                text: "This will delete the links.",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: "/Affiliate/Delete/" + eferralId,
                        method: "POST",
                    }).done(function (data) {
                        if (data.success) {
                            notifySucess(data.message);
                            table.draw();
                        } else {
                            notifyError(data.message);
                        }
                    });
                }
            });

        }

        function generateActionButtons(id) {
            let btns =
                '<div class="dropdown">' +
                '<button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">' +
                'Actions' +
                '</button>' +
                '<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">' +
                '<a class="dropdown-item" onclick="Update(\'' + id + '\')" href="#">Edit</a>' +
                '<a class="dropdown-item" onclick="remove(\'' + id + '\')" href="#">Remove</a>'
            '</div>' +
                '</div>';
            return btns;
        }
    </script>

}

Goalvisor/Views/Admin/Index.cshtml
@{ ViewData["Title"] = "Administrator";
                Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

<div class="text-center">
    <h1 class="display-4">Welcome Administrator</h1>
</div>

Goalvisor/Views/Admin/MyAccount.cshtml
@model Goalvisor.Models.ApplicationUser;

@{ ViewData["Title"] = "My Account";
                Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

<input type="hidden" asp-for="@Model.Id" />
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="personaldata-tab" data-toggle="tab" href="#personaldata" aria-controls="personaldata" aria-selected="true">Personal Data</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="telegram-tab" data-toggle="tab" href="#telegram" aria-controls="telegram" aria-selected="false">Telegram</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="download-tab" data-toggle="tab" href="#download" aria-controls="download" aria-selected="false">Download Data</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="deleteaccount-tab" data-toggle="tab" href="#deleteaccount" aria-controls="deleteaccount" aria-selected="false">Delete Account</a>
    </li>
</ul>
<div class="tab-content p-3 border-right border">
    <div class="tab-pane fade show active" id="personaldata" role="tabpanel" aria-labelledby="personaldata-tab">
        <partial name="~/Views/MyAccount/UpdateInfo.cshtml" />
    </div>
    <div class="tab-pane fade" id="telegram" role="tabpanel" aria-labelledby="telegram-tab">
        <h4>Connection status: Disconnected.</h4>
        <a href="#" class="btn btn-info"><img src="~/icons/telegram.png" width="32" height="32"> Connect Telegram</a>
    </div>
    <div class="tab-pane fade" id="download" role="tabpanel" aria-labelledby="download-tab">
        <button value="Download" class="btn btn-info"><i class="fas fa-download"></i> Download</button>
    </div>
    <div class="tab-pane fade" id="deleteaccount" role="tabpanel" aria-labelledby="deleteaccount-tab">
        <a onclick="remove()" class="btn btn-danger" href="#"> <i class="fas fa-trash"></i>Delete Account</a>
    </div>
</div>

@section Scripts{
    <script>

    let table = {};
        $(document).ready(function () {
            $('#spinner').hide();
        table = $('#subsDT').DataTable({
            "searchable": true,
            "bDestroy": true,
            "ordering": true,
            "serverSide": true,
            responsive: true,
            processing: true,
            sortable: true,
            ajax: {
                "url": "/MyAccount/Subscriptions/"+@Model.Id,
                "type": "POST"
            },
            columns: [
                {
                    name: 'Package Name',
                    data: 'packageName',
                    title: "Package Name",
                    sortable: true,
                },
                {
                    name: 'Duration',
                    data: 'duration',
                    title: "Duration",
                    sortable: true,
                },
                {
                    name: 'Start Date',
                    data: null,
                    title: "Start Date",
                    sortable: true,
                    render: function (data, type, full, meta) {
                        return full.startDate.substring(0, 10)
                    }
                },
                {
                    name: 'End Date',
                    data: null,
                    title: "End Date",
                    sortable: true,
                    render: function (data, type, full, meta) {
                        return full.endDate.substring(0, 10)
                    }
                },
                {
                    name: 'Status',
                    data: null,
                    title: "Status",
                    sortable: true,
                    render: function (data, type, full, meta) {
                        if (full.active) {
                            return "Active";
                        } else {
                            return "Inactive";
                        }
                    }
                }
            ]
        });

        $("#txtCopy").val('@ViewData["RootURL"]' + "Account/Join?r=" + '@Model.ReferralCode');
    });

        function updateInfo() {
            var modalSelector = GetLoaderModal(80);
            $(modalSelector).modal();

            $(modalSelector + "-content").load("/MyAccount/UpdateInfo/",
                function (response, status, xhr) {
                }
            );
        }

        $(function () {
            $('#btnCopy').click(function () {
                $('#txtCopy').focus();
                $('#txtCopy').select();
                document.execCommand('copy');
                notifySucess("Copied to clipboard!")
            });
        });

        function updateReferralId() {
            var modalSelector = GetLoaderModal(80);
            $(modalSelector).modal();

            $(modalSelector + "-content").load("/MyAccount/UpdateReferralId/",
                function (response, status, xhr) {
                }
            );
        }

        function gotoSubscriptionPlans() {
            window.location.href = "/Checkout/SelectPackage";
        }

        function remove() {
            Swal.fire({
                title: 'Are you sure?',
                text: "This will disable your access to the entire site.",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: "/Account/Delete/",
                        method: "POST",
                    }).done(function (data) {
                        if (data) {
                            notifySucess("Account disabled successfully.");
                            document.location.href ="/Account/Logout";
                        } else {
                            notifyError("Account disabled failed.");
                        }
                    });
                }
            });

        }
    </script>
}

Goalvisor/Views/Admin/Scanner.cshtml
@{ ViewData["Title"] = "Scanner";
                Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }

<h1>Scanner Page</h1>

<p>This page can only be seen by and admin or a logged in user with an active Subscription (Status Active and Not Expired)</p>