Goalvisor/Controllers/AdminController.cs
using Goalvisor.Services.Subscriptions;
using Goalvisor.Services.Users;
using Goalvisor.ViewModels.Core;
using Goalvisor.ViewModels.DataTables.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Threading.Tasks;

namespace Goalvisor.Controllers
{
    [Authorize(Policy = RunTimeElements.AdministratorRole)]
    public class AdminController : Controller
    {
        private readonly ISubscriptionsService _subscriptionsService;
        private readonly IUserService _userService;
        private readonly IConfiguration _configuration;

        public AdminController(ISubscriptionsService subscriptionsService, IUserService userService, IConfiguration configuration)
        {
            _subscriptionsService = subscriptionsService;
            _userService = userService;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> MyAccount()
        {
            var user = await _userService.GetByName(HttpContext.User.Identity.Name);
            ViewData["RootURL"] = _configuration.GetValue<string>("Root");
            return View(user);
        }

        public IActionResult Subscriptions()
        {
            return View();
        }

        public IActionResult Packages()
        {
            return View();
        }

        public IActionResult Affiliates()
        {
            return View();
        }

        public IActionResult Scanner()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PageData(DataTablesRequest request)
        {
            var result = await _subscriptionsService.DataTable(request);
            return new JsonResult(result);
        }
    }
}

Goalvisor/Controllers/EmailController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Goalvisor.Models;
using Goalvisor.Services.Email;
using Goalvisor.ViewModels.Core;
using Goalvisor.ViewModels.DataTables.Base;
using System.Threading.Tasks;

namespace Goalvisor.Controllers
{
    [Authorize(Policy = RunTimeElements.AdministratorRole)]
    public class EmailController : Controller
    {
        private IHostingEnvironment Environment;
        private readonly IEmailService _emailService;

        public EmailController(IEmailService emailService)
        {
            _emailService = emailService;
        }

        public IActionResult List()
        {
            return View();
        }

        public IActionResult Template()
        {
            var templatevm = new EmailTemplate();
            templatevm.TemplateName = "Registration Success Template.";
            templatevm.Subject = "Congratulations! You have registered successfully.";
            templatevm.Body = "Dear {recipient}, \n Thanks for your registration. \n Please activate your account by using this link \n {activationlink} \n\n\n warm regards \n ScannerSuite Team";
            return View(templatevm);
        }

        [HttpPost]
        public async Task<IActionResult> PageData(DataTablesRequest request)
        {
            var result = await _emailService.DataTable(request);
            return new JsonResult(result);
        }

        public async Task<IActionResult> Edit(int id)
        {
            EmailTemplate model;
            if (id != 0)
            {
                model = await _emailService.GetById(id);
                if (model == null)
                {
                    return BadRequest();
                }
            }
            else
            {
                model = new EmailTemplate();
            }
            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrUpdate(EmailTemplate emailTemplate)
        {
            var result = await _emailService.AddOrUpdate(emailTemplate);
            TempData["SuccessMsg"] = result.Message;
            return RedirectToAction("List");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await _emailService.DeleteById(id);
            TempData["SuccessMsg"] = result;
            return RedirectToAction("List");
        }
    }
}

Goalvisor/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Goalvisor.Services.Roles;
using Goalvisor.ViewModels;
using Goalvisor.ViewModels.Core;
using Goalvisor.ViewModels.DataTables.Base;
using System.Threading.Tasks;

namespace Goalvisor.Controllers
{
    [Authorize(Policy = RunTimeElements.AdministratorRole)]
    public class RolesController : Controller
    {
        private IRolesService _rolesSerice;

        public RolesController(IRolesService rolesSerice)
        {
            _rolesSerice = rolesSerice;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> PageData(DataTablesRequest request)
        {
            return new JsonResult(await _rolesSerice.DataTable(request));
        }

        public async Task<IActionResult> AddOrUpdate(int id)
        {
            IdentityRole<int> role;
            if (id > 0)
            {
                role = await _rolesSerice.GetById(id);
                if (role == null)
                {
                    return BadRequest();
                }
            }
            else
            {
                role = new IdentityRole<int>();
            }
            return PartialView(role);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrUpdate(IdentityRole<int> role)
        {
            ServiceResult result;
            if (role.Id == 0)
            {
                result = await _rolesSerice.Add(role);
            }
            else
            {
                result = await _rolesSerice.Update(role);
            }

            return new JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            var result = await _rolesSerice.Remove(id);
            return new JsonResult(result);
        }
    }
}

Goalvisor/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Goalvisor.Services.Roles;
using Goalvisor.Services.Subscriptions;
using Goalvisor.Services.Users;
using Goalvisor.ViewModels;
using Goalvisor.ViewModels.Core;
using Goalvisor.ViewModels.DataTables.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Goalvisor.Controllers
{
    [Authorize(Policy = RunTimeElements.AdministratorRole)]
    public class UsersController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRolesService _rolesService;
        private readonly ISubscriptionsService _subscriptionsService;

        public UsersController(IUserService userService, IRolesService rolesService,  ISubscriptionsService subscriptionsService)
        {
            _userService = userService;
            _rolesService = rolesService;
            _subscriptionsService = subscriptionsService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> PageData(DataTablesRequest request)
        {
            return new JsonResult(await _userService.DataTable(request));
        }

        public async Task<IActionResult> AddOrUpdate(int id)
        {
            UserVM user = new UserVM();
            if (id > 0)
            {
                var temp = await _userService.GetById(id);
                user.Id = temp.Id;
                user.FullName = temp.FullName;
                user.Email = temp.Email;
                user.UserName = temp.UserName;
                user.LockedOut = temp.LockoutEnabled && temp.LockoutEnd >= DateTime.Now;
            }
            return PartialView(user);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrUpdate(UserVM user)
        {
            ServiceResult result;
            if (user.Id <= 0)
            {
                result = await _userService.Add(user);
            }
            else
            {
                result = await _userService.Update(user);
            }
            return new JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            var result = await _userService.Remove(id);
            return new JsonResult(result);
        }

        [HttpPost]
        public async Task<Boolean> Revoke(int id)
        {
            Boolean result = await _userService.Revoke(id);
            return result;
        }

        [HttpPost]
        public async Task<Boolean> Restore(int id)
        {
            Boolean result = await _userService.Restore(id);
            return result;
        }

        public async Task<IActionResult> AssignRoles(int id)
        {
            var user = await _userService.GetById(id);
            if (user == null)
            {
                return BadRequest();
            }
            var assignRoleVM = new AssignRoleVM
            {
                UserId = user.Id,
                userName = user.FullName,
                Roles = await _rolesService.GetAll()
            };
            var userRoles = await _userService.GetRoles(user);
            foreach (var item in assignRoleVM.Roles)
            {
                if (userRoles.Contains(item.RoleName))
                {
                    item.UserInRole = true;
                }
            }
            return PartialView(assignRoleVM);
        }

        [HttpPost]
        public async Task<IActionResult> AssignRoles(int id, IEnumerable<string> roleIds)
        {
            var result = await _userService.UpdateRoles(id, roleIds);
            return new JsonResult(result);
        }

        [HttpPost]
        public async Task<IActionResult> AddSubscription(int id, int subscriptionId)
        {
            var user = await _userService.GetById(id);
            var subscription = await _subscriptionsService.GetById(subscriptionId);
            if (user == null || subscription == null)
            {
                return BadRequest();
            }
            var result = await _subscriptionsService.CreateSubscription(user, subscription);

            return new JsonResult(result);
        }
    }
}

Goalvisor/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authentication.Cookies;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="color-scheme" content="light dark">
    <title>@ViewData["Title"] - Goalvisor</title>

    <link href="~/css/Tivo/styles.css" rel="stylesheet">

    <link href="~/css/Tivo/bootstrap.css" rel="stylesheet">

    @*<link href="~/css/Tivo/fontawesome-all.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.1/css/all.min.css" />
    <link href="~/css/Tivo/swiper.css" rel="stylesheet">
    <link href="~/css/Tivo/magnific-popup.css" rel="stylesheet">


    <link rel="stylesheet" type="text/css" href="~/css/site.css?v=1.0" />
    <link rel="stylesheet" href="~/css/datatables.min.css" />
    <link rel="stylesheet" href="~/css/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/css/daterangepicker.css" />

    <!-- Bootstrap CSS -->
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-nightshade.css">*@

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700&display=swap&subset=latin-ext" rel="stylesheet">

</head>
<body>

    <header>
        <partial name="_NavMenu" />
    </header>
    <div class="container-fluid main-container">
        <main role="main" class="pb-3 pl-3 pr-3">
            @RenderBody()
            <div id="Global-Dynamic-Modals">
            </div>
        </main>
    </div>
    <div id="progress" class="modal123">
    </div>
    <footer id="footer" class="d-flex-column text-center" style=" background-color: #5f4dee;">
        <hr class="mt-0">
        <!--Social buttons-->
        <div class="text-center">
            <p class="text-white text-center font-weight-bold">Goalvisor</p>

        </div>
        <!--/.Social buttons-->
        <hr class="mb-0">
        <!--Footer Links-->
        <div class="container text-center text-md-center">
            <div class="row">
                <div class="text-center text-white p-4">
                    © 2021 Copyright:
                    <a class="text-reset text-white fw-bold" href="#">Goalvisor</a>
                </div>

            </div>
        </div>


        <!--/.Copyright-->
    </footer>


    <script src="~/js/Tivo/jquery.min.js"></script> <!-- jQuery for Bootstrap's JavaScript plugins -->
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/bootstrap-notify.min.js"></script>
    <script src="~/js/datatables.min.js" type="text/javascript"></script>
    <script src="~/js/sweetalert2.all.min.js" type="text/javascript"></script>
    <script src="~/js/moment-with-locales.js" type="text/javascript"></script>
    <script src="~/js/daterangepicker.min.js" type="text/javascript"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/modalUtils.js" asp-append-version="true"></script>


    <script src="~/js/Tivo/popper.min.js"></script> <!-- Popper tooltip library for Bootstrap -->
    <script src="~/js/Tivo/bootstrap.min.js"></script> <!-- Bootstrap framework -->
    <script src="~/js/Tivo/jquery.easing.min.js"></script> <!-- jQuery Easing for smooth scrolling between anchors -->
    <script src="~/js/Tivo/swiper.min.js"></script> <!-- Swiper for image and text sliders -->
    <script src="~/js/Tivo/jquery.magnific-popup.js"></script> <!-- Magnific Popup for lightboxes -->
    <script src="~/js/Tivo/validator.min.js"></script> <!-- Validator.js - Bootstrap plugin that validates forms -->
    <script src="~/js/Tivo/scripts.js"></script> <!-- Custom scripts -->
    <script>
        $(document).ready(function () {

            // This code uses `localStorage` to save "user prefers color" persistently
            // This key used is `user-prefers-color`, and should be one of:
            //  0 = only used at first trigger, to indicate firts time selection
            //  1 = user wants light mode
            //  2 = user wants dark mode
            // the key can also be deleted to indicate user has no preference.

            // function to toggle the css
            function toggle_color_scheme_css($mode) {
                // amend the body classes
                if ($mode == 'dark') {
                    $("html").removeClass('light').addClass("dark");
                    $("nav").removeClass("navbar-light").addClass('navbar-dark');
                    $("nav").removeClass("bg-white").addClass('bg-black');

                    $(".lda").removeClass('dark').addClass("light");
                    $(".lbl-ld").html("<i class='fas fa-sun' aria-hidden='true'> </i> Light");
                } else {
                    $("html").removeClass("dark").addClass('light');
                    $("nav").removeClass("navbar-dark").addClass('navbar-light');
                    $("nav").removeClass("bg-black").addClass('bg-white');
                    $(".lbl-ld").html("<i class='fa fa-moon' aria-hidden='true'></i> Dark");
                    $(".lda").removeClass('light').addClass("dark");
                }
                // if on user prefers color then update stored value
                $upc = window.localStorage.getItem('user-prefers-color');
                if ($upc !== null) {
                    if ($upc == 0) $("#css-save-btn").prop("checked", true);  // first time click
                    window.localStorage.setItem('user-prefers-color', ($mode == 'dark') ? 2 : 1);
                }
            }

            // function / listener action to toggle the button
            function update_color_scheme_css() {
                $upc = window.localStorage.getItem('user-prefers-color');
                if (($upc === null) || ($upc == 0)) {
                    $mode = (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) ? 'dark' : 'light';
                } else {
                    $mode = ($upc == 2) ? 'dark' : 'light';
                }
                $("#css-toggle-btn").prop("checked", ('dark' == $mode));
                toggle_color_scheme_css($mode);
            }

            // initial mode discovery & update button
            update_color_scheme_css();
            if (window.localStorage.getItem('user-prefers-color') !== null)
                $("#css-save-btn").prop("checked", true);

            // update every time it changes
            if (window.matchMedia) window.matchMedia("(prefers-color-scheme: dark)").addListener(update_color_scheme_css);

            // toggle button click code
            $("#css-toggle-btn").bind("click", function () {
                // disable further automatic toggles
                if (window.localStorage.getItem('user-prefers-color') === null)
                    window.localStorage.setItem('user-prefers-color', 0);
                // get current mode, i.e. does body have the `.dark`` classname
                $mode = $("html").hasClass("dark") ? 'light' : 'dark';
                toggle_color_scheme_css($mode);
            });

            // toggle button click code
            $("#css-save-btn").bind("click", function () {
                $chk = $("#css-save-btn").prop("checked");
                if ($chk) {
                    // user wants persistance, save current state
                    $upc = $("html").hasClass("dark") ? 2 : 1;
                    window.localStorage.setItem("user-prefers-color", $upc);
                } else {
                    // user doesn't want pesistace, delete saved key
                    window.localStorage.removeItem("user-prefers-color");
                }
            });

        });</script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Goalvisor/Views/Shared/_NavMenu.cshtml
@using Microsoft.AspNetCore.Identity
@using Goalvisor.ViewModels.Core;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject Goalvisor.Services.Users.IUserService userService;

<nav class="navbar navbar-expand-lg  navbar-toggleable-lg navbar-light bg-white border-bottom box-shadow mb-3" >
 
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Goalvisor</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
            <div class="navbar-nav" id="navbar-list-2">
                @if (User.IsInRole(RunTimeElements.AdministratorRole) || User.IsInRole(RunTimeElements.SubscriberRole))
                {
                    <a class="nav-item nav-link active" asp-area="" asp-controller="Scanner" asp-action="Index">Scanner</a>
                    @if (User.IsInRole(RunTimeElements.SubscriberRole))
                    {
                        <div class="nav-item dropdown show">
                            <a data-toggle="dropdown" class="nav-link dropdown-toggle active" aria-expanded="false" asp-area="" asp-controller="Affiliate" asp-action="Index">Affiliate</a>

                            <div class="dropdown-menu">
                                <a class="nav-item nav-link active" aria-expanded="false" asp-area="" asp-controller="Affiliate" asp-action="Index">Refer a Friend</a>

                                <a class="nav-item nav-link active" asp-area="" asp-controller="Affiliate" asp-action="MyReferralLinks">My Referral Links</a>
                            </div>
                        </div> }
                    else if (User.IsInRole(RunTimeElements.AdministratorRole))
                    {
                        <div class="nav-item dropdown show">
                            <a data-toggle="dropdown" class="nav-link dropdown-toggle active" aria-expanded="false" asp-area="" asp-controller="Affiliate" asp-action="Index">Affiliate</a>

                            <div class="dropdown-menu">
                                <a class="nav-item nav-link active" asp-area="" asp-controller="Affiliate" asp-action="List">Referral Links</a>
                            </div>
                        </div>

                        <div class="nav-item dropdown show">
                            <a data-toggle="dropdown" class="nav-link dropdown-toggle active" aria-expanded="false" asp-area="" asp-controller="Email" asp-action="List">Email Template</a>

                            <div class="dropdown-menu">
                                <a class="nav-item nav-link active" asp-area="" asp-controller="Email" asp-action="List">Template List</a>
                                <a class="nav-item nav-link active" asp-area="" asp-controller="Email" asp-action="Template">Create New Template</a>
                            </div>
                        </div>}
                }

                @if (Context.User.Identity.IsAuthenticated)
                {
                    if (!(await userService.HasActiveSubscription(Context.User.Identity.Name)))
                    {
                        <span class="nav-item nav-link active">No Active subscription!</span>

                        <a class="button-glow" asp-controller="Account" asp-action="Join">Start my free trial</a>
                    }
                }
            </div>

            @if (SignInManager.IsSignedIn(User))
            {
                <div class="navbar-nav ml-auto">
                    <div class="nav-item dropdown show">
                        <a class="nav-link dropdown-toggle user-action" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i>
                            Hello, @User.Identity.Name ! <b class="caret"></b>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @if (User.IsInRole(RunTimeElements.AdministratorRole))
                            {

                                <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Index">Manage Users</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="Index">Manage Roles</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Subscriptions" asp-action="Index">Manage Subscription</a>}
                            <a class="nav-item nav-link active" asp-controller="MyAccount" asp-action="Index"><i>...</i> My Account</a>
                            <a class="nav-item nav-link active" asp-controller="Subscriptions" asp-action="MySubscriptions"><i class="fas fa-file-invoice"></i> Subscriptions</a>
                          
                            <a class="nav-item nav-link active" asp-area="" asp-controller="Account" asp-action="Logout"><i class="fas fa-sign-out-alt"></i> Logout</a>
                        </div>

                    </div>
                </div> }
            else
            {
                <div class="navbar-nav ml-auto navbar-logout">
                    <a class="button-glow" asp-controller="Account" asp-action="Join">Start my free trial</a>
                    <a class="button-ghost" asp-controller="Account" asp-action="Login">Login</a>
                </div>
            }
        </div>
    </div>
</nav>

<style>
    .button-glow {
        background: linear-gradient(-45deg, #00A900, darkgreen, #00ff21);
        background-size: 400% 400%;
        animation: gradient 15s ease infinite;
        width: 175px;
        height: 35px;
        border-radius: 20px;
        margin: 0 auto;
        padding: 0;
        display: inline-block;
        line-height: 35px;
        text-align: center;
        color: white;
        font-weight: bold;
        text-decoration: none;
    }
        .button-glow:hover {
            text-decoration: none;
            color: darkgreen;
            transition: all 0.4s ease 0s;
        }
    .button-ghost {
        color: #494949 !important;
        text-decoration: none;
        background: #ffffff;
        padding: 20px;
        border: 1px solid #494949 !important;
        border-radius: 20px;
        width: 125px;
        height: 35px;
        margin: 0 auto;
        padding: 0;
        display: inline-block;
        line-height: 35px;
        text-align: center;
        color: white;
        font-weight: bold;
        font-weight: 700;
        font-size: small;
        margin-left: 15px;
        font-size: 14px;
    }
    .button-ghost:hover {
        text-decoration: none;
        color: #fff!important;
        background-color:#087ccd;
    }
    .navbar-dark .navbar-brand:hover, .navbar-dark .navbar-brand:focus {
         color: #333; 
    }

    .navbar-dark .navbar-brand {
         color: #333; 
    }


    @@keyframes gradient {
	0% {
		background-position: 0% 50%;
	}
	50% {
		background-position: 100% 50%;
	}
	100% {
		background-position: 0% 50%;
	}
}
</style>

Goalvisor/Views/Shared/_NavMenuAdmin.cshtml
@using Microsoft.AspNetCore.Identity
@using Goalvisor.ViewModels.Core;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject Goalvisor.Services.Users.IUserService userService;

<nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light bg-white border-bottom box-shadow mb-3">

    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Goalvisor</a>

        <button class="navbar-toggler ml-auto mr-3" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
            <div class="navbar-nav" id="navbar-list-2">
                <a asp-area="" asp-controller="Admin" asp-action="Index" class="nav-item nav-link active">Home</a>
                <a class="nav-item nav-link active" asp-area="" asp-controller="Admin" asp-action="Guide">Guide</a>
                <a class="nav-item nav-link active" asp-area="" asp-controller="Admin" asp-action="Support">Support</a>
                <a class="nav-item nav-link active" asp-area="" asp-controller="Admin" asp-action="Scanner">Scanner</a>
                <div class="nav-item dropdown show">
                    <a data-toggle="dropdown" class="nav-link dropdown-toggle active" aria-expanded="false" asp-area="" asp-controller="Affiliate" asp-action="Index">Affiliate</a>

                    <div class="dropdown-menu">
                        <a class="nav-item nav-link active" asp-area="" asp-controller="Admin" asp-action="Affiliates">Manage Referral</a>
                    </div>
                </div>
                <div class="nav-item dropdown show">
                    <a data-toggle="dropdown" class="nav-link dropdown-toggle active" aria-expanded="false" asp-area="" asp-controller="Email" asp-action="List">Email Template</a>

                    <div class="dropdown-menu">
                        <a class="nav-item nav-link active" asp-area="" asp-controller="Email" asp-action="List">Template List</a>
                        <a class="nav-item nav-link active" asp-area="" asp-controller="Email" asp-action="Template">New Template</a>
                    </div>
                </div>
            </div>

            @if (SignInManager.IsSignedIn(User))
            {
                <div class="navbar-nav ml-auto">
                    <div class="nav-item dropdown show">
                        <a data-toggle="dropdown" class="nav-link dropdown-toggle user-action" aria-expanded="false">
                            <i class="fas fa-user"></i>
                            Hello, @User.Identity.Name ! <b class="caret"></b>
                        </a>
                        <div class="dropdown-menu">

                            <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Index"><i class="fas fa-user"></i> Manage Users</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="Index"><i class="fas fa-cogs"></i> Manage Roles</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Subscriptions">Manage Subscription</a>
                            <a class="nav-item nav-link active" asp-controller="Admin" asp-action="MyAccount"><i>...</i> My Account</a>

                            <a class="nav-item nav-link active" asp-area="" asp-controller="Account" asp-action="Logout"><i class="fas fa-sign-out-alt"></i> Logout</a>
                        </div>
                    </div>
                </div> }
            else
            { <div class="navbar-nav ml-auto navbar-logout">
                    <a class="nav-item nav-link active" asp-controller="Account" asp-action="Login">Login</a>
                </div>}
        </div>
        <form class="form-inline ">
            <div class="custom-control custom-switch" title="" data-toggle="tooltip" data-placement="left" data-original-title="Toggle Dark Mode">

                <a href="#" class="btn btn-dark lda">

                    <label class="lbl-ld" for="css-toggle-btn"><i class="fa fa-sun" aria-hidden="true"></i>Light</label>
                </a>

                <input type="checkbox" class="custom-control-input" style="visibility:hidden!important" id="css-toggle-btn">
            </div>
            <div hidden class="custom-control custom-switch" title="" data-toggle="tooltip" data-placement="left" data-original-title="Remember my preference">
                <input type="checkbox" class="custom-control-input" id="css-save-btn" checked>
                <label class="custom-control-label" for="css-save-btn"></label>
            </div>
        </form>

    </div>

</nav> 